version: '3.3'

services:
  web:
    build: .
    depends_on:
      - db
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/web/
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env